# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('province', models.DateField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
