# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('percentage', models.FloatField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
