# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0001_initial'),
        ('events_type', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=8)),
                ('seat', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('assistance', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.IntegerField()),
                ('environment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='environment.Environment')),
                ('event_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events_type.EventsType')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
