# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ruc',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='seat',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
