# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160528_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='environment',
        ),
    ]
