# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
        ('events', '0008_remove_event_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='environment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='environment.Environment'),
        ),
    ]
