# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0009_event_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
