# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
        ('events', '0010_auto_20160601_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='price_invited',
        ),
        migrations.AddField(
            model_name='event',
            name='price_member',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='event',
            name='environment',
        ),
        migrations.AddField(
            model_name='event',
            name='environment',
            field=models.ManyToManyField(to='environment.Environment'),
        ),
    ]
