# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
        ('events', '0011_auto_20160603_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='headquarter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='headquarters.Headquarters'),
        ),
    ]
