# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('payment_documents', '0001_initial'),
        ('bungalow', '0002_auto_20160603_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='BungalowReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(null=True)),
                ('departure_date', models.DateField(null=True)),
                ('check_in', models.TimeField(null=True)),
                ('check_out', models.TimeField(null=True)),
                ('price', models.FloatField(null=True)),
                ('bungalow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bungalow.Bungalow')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
                ('payment_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_documents.Payment_Document')),
            ],
        ),
    ]
