# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bungalow', '0002_auto_20160603_1203'),
        ('payment_documents', '0001_initial'),
        ('members', '0002_auto_20160602_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('price', models.FloatField()),
                ('bungalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bungalow.Bungalow')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
                ('payment_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_documents.Payment_Document')),
            ],
        ),
    ]
