# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bungalow',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bungalow',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bungalow',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bungalow',
            name='check_out',
            field=models.TimeField(null=True),
        ),
    ]
