# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow_reservation', '0002_auto_20160603_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bungalow',
            new_name='BungalowReservation',
        ),
    ]
