# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow_reservation', '0003_auto_20160603_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungalowreservation',
            name='bungalow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bungalow.Bungalow'),
        ),
        migrations.AlterField(
            model_name='bungalowreservation',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AlterField(
            model_name='bungalowreservation',
            name='payment_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_documents.Payment_Document'),
        ),
        migrations.AlterField(
            model_name='bungalowreservation',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
