# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungalow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungalow',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponible'), (2, 'Mantenimiento'), (3, 'Proximamente'), (4, 'Detenido')]),
        ),
    ]
