# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_types', '0001_initial'),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField()),
                ('attendance', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_types.ActivityType')),
                ('enviroment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Environment')),
            ],
        ),
    ]
