# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [

    ]
