# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
