# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_types', '0002_auto_20160526_0648'),
        ('activities', '0002_remove_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activity_types.ActivityType'),
            preserve_default=False,
        ),
    ]
