# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.BigIntegerField()),
                ('businessName', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('province', models.CharField(max_length=120)),
                ('distric', models.CharField(max_length=120)),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('effectiveTime', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contactName', models.CharField(max_length=120)),
                ('contactPhone', models.BigIntegerField()),
            ],
        ),
    ]
