# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='registrationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
    ]
