# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20160520_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='idProvider',
            field=models.BigIntegerField(),
        ),
    ]
