# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20160522_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='businessName',
            field=models.CharField(max_length=120),
        ),
    ]
