# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20160525_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='effectiveTime',
            field=models.IntegerField(choices=[(30, '1 Mes'), (90, '3 Meses'), (180, '6 Meses'), (365, '12 meses')], default=30),
        ),
    ]
