# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20160520_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='idProvider',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ruc',
            field=models.BigIntegerField(),
        ),
    ]
