# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 00:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='effectiveTime',
        ),
        migrations.AlterField(
            model_name='provider',
            name='ruc',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
