# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20160520_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contactPhone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
