# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20160601_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ruc',
            field=models.BigIntegerField(),
        ),
    ]
