# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20160601_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='postal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
