# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_provider_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='postal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='region',
            field=models.CharField(max_length=120),
        ),
    ]
