# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('initialDate', models.DateField()),
                ('finalDate', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.MembershipType')),
            ],
        ),
    ]
