# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_document_type', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('paternalLastName', models.CharField(max_length=20)),
                ('maternalLastName', models.CharField(max_length=20)),
                ('document_number', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('initialDate', models.DateField()),
                ('finalDate', models.DateField()),
                ('status', models.IntegerField()),
                ('identity_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_document_type.Identity_Document_Type')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.MembershipType')),
            ],
        ),
    ]
