# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialDate', models.DateField()),
                ('finalDate', models.DateField()),
                ('status', models.IntegerField()),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.MembershipType')),
            ],
        ),
    ]
