# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarters',
            name='status',
            field=models.IntegerField(default=datetime.datetime(2016, 6, 2, 3, 34, 57, 117771, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
