# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('observations', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fine',
            name='fine_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fine.FineType'),
        ),
        migrations.AddField(
            model_name='fine',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
