# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='headquarter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='headquarters.Headquarters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentreservation',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Environment'),
        ),
    ]
