# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityTypes',
            new_name='ActivityType',
        ),
    ]
