# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_types', '0002_auto_20160526_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='status',
            field=models.DateTimeField(null=True),
        ),
    ]
