from django.core.management.base import BaseCommand
from Locations.models import *

class Command(BaseCommand):
    help = 'This command will seed the database (Location)'

    def handle(self, *args, **options):
        print('\n  Location Seeder is running...\n')

        print('    Deleting...')
        self.cleanDB()

        print('    Inserting...')
        self.insertData()

    def cleanDB(self):
        Region.objects.all().delete()
        print('    Data has been deleted\n')

    def insertData(self):
        #Región Amazonas
        amazonas = Region(name = 'Amazonas')
        amazonas.save()
        #Provincia Chachapoyas
        chachapoyas = Province (region =amazonas,name = 'Chachapoyas')
        chachapoyas.save()
        #Distritos
        distrito1 = District(province = chachapoyas,name = 'Asunción')
        distrito1.save()
        distrito2 = District(province = chachapoyas,name = 'Balsas')
        distrito2.save()
        distrito3 = District(province = chachapoyas,name = 'Chachapoyas')
        distrito3.save()
        distrito4 = District(province = chachapoyas,name = 'Cheto')
        distrito4.save()
        distrito5 = District(province = chachapoyas,name = 'Chiliquín')
        distrito5.save()
        distrito6 = District(province = chachapoyas,name = 'Chuquibamba')
        distrito6.save()
        distrito7 = District(province = chachapoyas,name = 'Granada')
        distrito7.save()
        distrito8 = District(province = chachapoyas,name = 'Huancas')
        distrito8.save()
        distrito9 = District(province = chachapoyas,name = 'La Jalca')
        distrito9.save()
        distrito10 = District(province = chachapoyas,name = 'Leymebamba')
        distrito10.save()
        distrito11 = District(province = chachapoyas,name = 'Levanto')
        distrito11.save()
        distrito12 = District(province = chachapoyas,name = 'Magdalena')
        distrito12.save()
        distrito13 = District(province = chachapoyas,name = 'Mariscal Castilla')
        distrito13.save()
        distrito14 = District(province = chachapoyas,name = 'Molinopampa')
        distrito14.save()
        distrito15 = District(province = chachapoyas,name = 'Montevideo')
        distrito15.save()
        distrito16 = District(province = chachapoyas,name = 'Olleros')
        distrito16.save()
        distrito17 = District(province = chachapoyas,name = 'Quinjalca')
        distrito17.save()
        distrito18 = District(province = chachapoyas,name = 'San Francisco de Daguas')
        distrito18.save()
        distrito19 = District(province = chachapoyas,name = 'San Isidro de Maino')
        distrito19.save()
        distrito20 = District(province = chachapoyas,name = 'Soloco')
        distrito20.save()
        distrito21 = District(province = chachapoyas,name = 'Sonche')
        distrito21.save()
        #Provincia Bagua
        bagua = Province (region =amazonas,name = 'Bagua')
        bagua.save()
        #Distritos
        distrito1 = District(province = bagua,name = 'Bagua')
        distrito1.save()
        distrito1 = District(province = bagua,name = 'La peca')
        distrito1.save()
        distrito1 = District(province = bagua,name = 'Aramango')
        distrito1.save()
        distrito1 = District(province = bagua,name = 'Copallín')
        distrito1.save()
        distrito1 = District(province = bagua,name = 'El Parco')
        distrito1.save()
        distrito1 = District(province = bagua,name = 'Imaza')
        distrito1.save()
        #Provincia Bongará
        bongora = Province (region =amazonas,name = 'Bongorá')
        bongora.save()
        #Distritos
        distrito1 = District(province = bongora,name = 'Jumbilla')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Chisquilla')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Churuja')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Corosha')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Cuispes')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Florida')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Jazán')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Recta')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'San Carlos')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Shipasbamba')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Valera')
        distrito1.save()
        distrito1 = District(province = bongora,name = 'Yambrasbamba')
        distrito1.save()
        #Provincia Condorcanqui
        condorcanqui = Province (region =amazonas,name = 'Condorcanqui')
        condorcanqui.save()
        #Distritos
        distrito1 = District(province = condorcanqui,name = 'El Cenepa')
        distrito1.save()
        distrito1 = District(province = condorcanqui,name = 'Nieva')
        distrito1.save()
        distrito1 = District(province = condorcanqui,name = 'Río Santiago')
        distrito1.save()
        #Provincia Luya
        luya = Province (region =amazonas,name = 'Luya')
        luya.save()
        #Distritos
        distrito1 = District(province = luya,name = 'Camporredondo')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Cocabamba')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Colcamar')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Conila')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Inquilpata')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Lámud')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Longuita')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Lonya Chico')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Luya')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Luya Viejo')
        distrito1.save()
        distrito1 = District(province = luya,name = 'María')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Ocalli')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Ocumal')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Pisuquía')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Providencia')
        distrito1.save()
        distrito1 = District(province = luya,name = 'San Cristóbal')
        distrito1.save()
        distrito1 = District(province = luya,name = 'San Francisco del Yeso')
        distrito1.save()
        distrito1 = District(province = luya,name = 'San Jerónimo')
        distrito1.save()
        distrito1 = District(province = luya,name = 'San Juan de Lopecancha')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Santa Catalina')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Santo Tomás')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Tingo')
        distrito1.save()
        distrito1 = District(province = luya,name = 'Trita')
        distrito1.save()
        #Provincia Rodríguez de Mendoza
        rodriguez = Province (region =amazonas,name = 'Rodríguez de Mendoza')
        rodriguez.save()
        #Distritos
        distrito1 = District(province = rodriguez,name = 'San Nicolás')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Chirimoto')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Cochamal')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Huambo')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Limabamba')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Longar')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Mariscal Benavides')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Milpuc')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Omia')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Santa Rosa')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Totora')
        distrito1.save()
        distrito1 = District(province = rodriguez,name = 'Vista Alegre')
        distrito1.save()
        #Provincia Utcubamba
        utcubamba = Province (region =amazonas,name = 'Utcubamba')
        utcubamba.save()
        #Distritos
        distrito1 = District(province = utcubamba,name = 'Bagua Grande')
        distrito1.save()
        distrito1 = District(province = utcubamba,name = 'Cajaruro')
        distrito1.save()
        distrito1 = District(province = utcubamba,name = 'Cumba')
        distrito1.save()
        distrito1 = District(province = utcubamba,name = 'El Milagro')
        distrito1.save()
        distrito1 = District(province = utcubamba,name = 'Jamalca')
        distrito1.save()
        distrito1 = District(province = utcubamba,name = 'Lonya Grande')
        distrito1.save()
        distrito1 = District(province = utcubamba,name = 'Yamón')
        distrito1.save()

        #Regin Áncash
        ancash = Region(name = 'Áncash')
        ancash.save()
        #Provincias
        huaraz = Province (region =ancash,name = 'Huaraz')
        huaraz.save()
        aija = Province (region =ancash,name = 'Aija')
        aija.save()
        raimondi = Province (region =ancash,name = 'Antonio Raimondi')
        raimondi.save()
        asuncion = Province (region =ancash,name = 'Asunción')
        asuncion.save()
        bolognesi = Province (region =ancash,name = 'Bolognesi')
        bolognesi.save()
        carhuaz = Province (region =ancash,name = 'Carhuaz')
        carhuaz.save()


        apurimac = Region(name = 'Apurimac')
        apurimac.save()
        arequipa = Region(name = 'Arequipa')
        arequipa.save()
        ayacucho = Region(name = 'Ayacucho')
        ayacucho.save()
        cajamarca = Region(name = 'Cajamarca')
        cajamarca.save()
        callao = Region(name = 'Callao')
        callao.save()
        cusco = Region(name = 'Cusco')
        cusco.save()
        huancavelica = Region(name = 'Huancavelica')
        huancavelica.save()
        huanuco = Region(name = 'Huánuco')
        huanuco.save()
        ica = Region(name = 'Ica')
        ica.save()
        junin = Region(name = 'Junín')
        junin.save()
        libertad = Region(name = 'La Libertad')
        libertad.save()
        lambayeque = Region(name = 'Lambayeque')
        lambayeque.save()
        lima = Region(name = 'Lima')
        lima.save()
        loreto = Region(name = 'Loreto')
        loreto.save()
        madre = Region(name = 'Madre de Dios')
        madre.save()
        moquegua = Region(name = 'Moquegua')
        moquegua.save()
        pasco = Region(name = 'Pasco')
        pasco.save()
        piura = Region(name = 'Piura')
        piura.save()
        puno = Region(name = 'Puno')
        puno.save()
        martin = Region(name = 'San Martín')
        martin.save()
        tacna = Region(name = 'Tacna')
        tacna.save()
        tumbes = Region(name = 'Tumbes')
        tumbes.save()



        print('    Data has been inserted\n')
