# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='region_id',
            new_name='region',
        ),
    ]
