# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0002_auto_20160603_1350'),
        ('identity_document_type', '0001_initial'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('paternalLastName', models.TextField(max_length=200)),
                ('maternalLastName', models.TextField(max_length=200)),
                ('document_number', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('state', models.IntegerField()),
                ('identity_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_document_type.Identity_Document_Type')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.Membership')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
