# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('identity_document_type', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('surname', models.TextField(max_length=200)),
                ('document_number', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('state', models.IntegerField()),
                ('identity_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_document_type.Identity_Document_Type')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.Membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
