# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('surname', models.TextField(max_length=200)),
                ('dni', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('state', models.IntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.Membership')),
            ],
        ),
    ]
