# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('products', '0002_product_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ManyToManyField(to='providers.Provider'),
        ),
    ]
