# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160522_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='anual_stock',
            new_name='actual_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
