# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_application', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
                ('membership_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_application.Membership_Application')),
            ],
        ),
    ]
