# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BungalowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bungalow',
            name='bungalow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bungalows.BungalowType'),
        ),
    ]
