# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoBungalow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.FloatField()),
                ('aforo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bungalow',
            name='tipoBungalow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bungalows.TipoBungalow'),
        ),
    ]
