# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bungalows', '0002_auto_20160506_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bungalow',
            old_name='bungalow_type_id',
            new_name='bungalow_type',
        ),
    ]
